seed_everything: true
trainer:
  accelerator: gpu
  strategy: ddp_find_unused_parameters_true
  devices: [0]
  num_nodes: 1
  precision: 16-mixed
  max_epochs: 50
  check_val_every_n_epoch: 1
  num_sanity_val_steps: 1
  log_every_n_steps: 10

  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        dirpath: "/aifs4su/mmcode/codeclm/checkpoints/mot/simvq/exp1.6" # Please specify your own path
        save_top_k: -1 # save all checkpoints
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: step
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      project: "mot"
      name: "exp1.6"
      save_dir: "/aifs4su/mmcode/codeclm/checkpoints/mot/simvq/exp1.6"

model:
  class_path: taming.models.vq_audio.VQModel
  init_args:
    ddconfig:
      causal: true
      dimension: 512
    
    quantconfig:
      target: taming.modules.vqvae.quantize.SimVQ1D
      params:
        n_e: 65536
        e_dim: 512
        beta: 0.25
        legacy: false

    lossconfig:
      target: taming.modules.losses.stft.VQSTFTWithDiscriminator
      params:
        disc_conditional: False
        disc_in_channels: 1
        disc_start: 0 # from 0 epoch
        codebook_enlarge_ratio: 0
        codebook_enlarge_steps: 2000
        sample_rate: 24000
        commit_weight: 250.0
        gen_loss_weight: 1.0
        mel_loss_coeff: 45.0
        mrd_loss_coeff: 1.0
    
    sample_rate: 24000
    target_bandwidths: None
    audio_normalize: false
    segment: None
    learning_rate: 1e-4
    scheduler_type: "None"
    use_ema: true

data:
  class_path: main.PadDataModuleFromConfig
  init_args:
    batch_size: 20
    num_workers: 8
    train:
      target: taming.data.annealing.AnnealingTrain
      params:
        config:
          sample_rate: 24000
          channels: 1
          clip_seconds: 3
          filelist: /aifs4su/mmdata/rawdata/codeclm/music/ytblrc/train.txt
    validation:
      target: taming.data.annealing.AnnealingDev
      params:
        config:
          sample_rate: 24000
          channels: 1
          clip_seconds: 3
          filelist: /aifs4su/mmdata/rawdata/codeclm/music/ytblrc/test.txt
    test:
      target: taming.data.annealing.AnnealingTest
      params:
        config:
          sample_rate: 24000
          channels: 1
          clip_seconds: -1
          filelist: /aifs4su/mmdata/rawdata/codeclm/music/ytblrc/test.txt

ckpt_path: null # to resume